export const labels: Record<string, string> = {
  oak_door:'橡木门', copper_door:'铜门', oak_fence_gate:'橡木栅栏门', oak_pressure_plate:'橡木压力板', cauldron:'炼药锅', water_cauldron:'水炼药锅', lava_cauldron:'熔岩炼药锅', powder_snow_cauldron:'细雪炼药锅', beehive:'蜂箱', bee_nest:'蜂巢', respawn_anchor:'重生锚', end_portal_frame:'末地传送门框架', waxed_copper_golem_statue:'涂蜡铜傀儡雕像', copper_golem_statue:'铜傀儡雕像',
  stone: '石头', smooth_stone: '平滑石', glass: '玻璃', white_concrete: '白色混凝土', light_gray_concrete: '浅灰混凝土', red_concrete: '红色混凝土', blue_concrete: '蓝色混凝土', white_wool: '白色羊毛', slime_block: '黏液块', honey_block: '蜂蜜块', obsidian: '黑曜石', bedrock: '基岩', glowstone: '荧石', sea_lantern: '海晶灯', redstone_wire: '红石粉', redstone_block: '红石块', redstone_torch: '红石火把', redstone_wall_torch: '墙上红石火把', lever: '拉杆', stone_button: '石质按钮', oak_button: '橡木按钮', repeater: '中继器', comparator: '比较器', observer: '侦测器', redstone_lamp: '红石灯', copper_bulb: '铜灯', exposed_copper_bulb: '斑驳铜灯', weathered_copper_bulb: '锈蚀铜灯', oxidized_copper_bulb: '氧化铜灯', target: '标靶', piston: '活塞', sticky_piston: '黏性活塞', hopper: '漏斗', chest: '箱子', trapped_chest: '陷阱箱', barrel: '木桶', dropper: '投掷器', dispenser: '发射器', crafter: '合成器', furnace: '熔炉', daylight_detector: '阳光探测器', sculk_sensor: '幽匿感测体', calibrated_sculk_sensor: '校频幽匿感测体', iron_door: '铁门', oak_trapdoor: '橡木活板门', iron_trapdoor: '铁活板门', note_block: '音符盒', powered_rail: '动力铁轨', rail: '铁轨', detector_rail: '探测铁轨', activator_rail: '激活铁轨', lightning_rod: '避雷针', lectern: '讲台', stone_pressure_plate: '石质压力板', heavy_weighted_pressure_plate: '重质测重压力板', light_weighted_pressure_plate: '轻质测重压力板', tripwire_hook: '绊线钩', tripwire: '绊线'
};
export const shortName = (name: string) => name.replace('minecraft:', '');
for (const waxed of [false,true]) for (const [age,label] of [['',''],['exposed_','斑驳'],['weathered_','锈蚀'],['oxidized_','氧化']])
  labels[(waxed?'waxed_':'')+age+'copper_chest']=(waxed?'涂蜡':'')+label+'铜箱';
export const blockLabel = (name: string) => labels[shortName(name)] ?? shortName(name).replaceAll('_', ' ');
export const propertyLabels: Record<string, string> = { facing: '朝向', face: '附着面', delay: '延迟 / 红石刻', mode: '工作模式', triggered: '已触发', powered: '激活', lit: '亮起', locked: '锁定', power: '强度', north: '北侧', south: '南侧', east: '东侧', west: '西侧', extended: '伸出', waterlogged: '含水', axis: '轴向', half: '半部', shape: '形状', type: '类型', open: '开启', enabled: '启用', inverted:'反向模式', hinge:'门轴', has_book:'放有书本', in_wall:'嵌入墙体', level:'装填等级', honey_level:'蜂蜜等级', charges:'充能次数', eye:'放有末影之眼', copper_golem_pose:'雕像姿态' };
export const valueLabels: Record<string, string> = { north: '北 −Z', south: '南 +Z', east: '东 +X', west: '西 −X', up: '上 +Y', down: '下 −Y', floor: '地面', ceiling: '天花板', wall: '墙面', compare: '比较', subtract: '减法', true: '是', false: '否', none: '无连接', side: '平接', upper:'上半部', lower:'下半部', top:'上', bottom:'下', left:'左', right:'右', standing:'站立', sitting:'坐下', running:'奔跑', star:'星形' };
export const favorites = ['redstone_wire','repeater','comparator','redstone_torch','lever','stone_button','observer','redstone_lamp','copper_bulb','piston','sticky_piston','redstone_block','white_concrete','stone','glass','slime_block','honey_block','target','stone_pressure_plate','oak_door','iron_door','daylight_detector','lectern','lightning_rod'];

Object.assign(valueLabels, {north_south:'南北直轨',east_west:'东西直轨',ascending_east:'向东上坡',ascending_west:'向西上坡',ascending_north:'向北上坡',ascending_south:'向南上坡',south_east:'东南弯轨',south_west:'西南弯轨',north_west:'西北弯轨',north_east:'东北弯轨'});
