import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Play, Pause, StepForward, SkipForward, RotateCcw, MousePointer2, Box, Eraser, Crosshair, Hand, Undo2, Redo2, FolderOpen, Save, Plus, Search, Layers, RotateCw, Maximize, Eye, Grid2X2, ChevronDown, Cable, CircleHelp, Copy, ClipboardPaste, Cpu, X, ExternalLink } from 'lucide-react';
import { connection, downloadFile, posKey, type Pos, type BlockDef, type Status } from './api';
import { blockLabel, favorites, propertyLabels, shortName, valueLabels } from './blockLabels';
import { CircuitViewport } from './viewport';
import { Waveform } from './waveform';
import { EnvironmentControls } from './environmentControls';
import { InventoryControls } from './inventoryControls';
import './styles.css';

type Tool = 'select'|'place'|'erase'|'probe'|'interact';
const tools: { id: Tool; label: string; icon: typeof Box; key: string }[] = [{id:'select',label:'选择',icon:MousePointer2,key:'1'},{id:'place',label:'放置',icon:Box,key:'2'},{id:'erase',label:'移除',icon:Eraser,key:'3'},{id:'probe',label:'探针',icon:Crosshair,key:'4'},{id:'interact',label:'操作',icon:Hand,key:'5'}];
const blockIcon = (name: string) => { const n=shortName(name);return n==='redstone_wire'?'╋':n==='repeater'?'⇥':n==='comparator'?'▷':n.includes('torch')?'♟':n==='lever'?'╱':n.includes('button')?'▰':n==='observer'?'◉':n.includes('lamp')?'▦':n.includes('bulb')?'▥':n==='redstone_block'?'◆':n==='glass'?'◇':'▣'; };
function App() {
  const [status,setStatus]=useState<Status>(connection.status),[connected,setConnected]=useState(false),[catalog,setCatalog]=useState(connection.catalog),[tool,setTool]=useState<Tool>('select'),[block,setBlock]=useState('minecraft:redstone_wire'),[search,setSearch]=useState(''),[category,setCategory]=useState('常用'),[layer,setLayer]=useState(1),[cutaway,setCutaway]=useState(false),[selected,setSelected]=useState<Pos|null>(null),[selectedDef,setSelectedDef]=useState<BlockDef|null>(null),[hover,setHover]=useState<Pos|null>(null),[fps,setFps]=useState(0),[toast,setToast]=useState(''),[help,setHelp]=useState(false),[menu,setMenu]=useState(false),[properties,setProperties]=useState<Record<string,string>>({facing:'west',face:'floor'}),[clipboard,setClipboard]=useState<BlockDef|null>(null);
  const viewportRef=useRef<HTMLDivElement>(null), view=useRef<CircuitViewport|null>(null), importRef=useRef<HTMLInputElement>(null), current=useRef({tool,block,properties,selected});current.current={tool,block,properties,selected};
  const notify=(message:string)=>{setToast(message);};
  const command=async(cmd:string,body:Record<string,unknown>={})=>{try{return await connection.request(cmd,body);}catch(error){notify(error instanceof Error?error.message:String(error));return undefined;}};
  const callbacks=useRef({command});callbacks.current={command};
  useEffect(()=>{
    const onStatus=()=>{setStatus({...connection.status});setConnected(connection.connected);}; const onCatalog=()=>setCatalog([...connection.catalog]);const onError=(event:Event)=>notify((event as CustomEvent<string>).detail);
    const refreshSelection=()=>{const p=current.current.selected;const cell=p?connection.cells.get(posKey(p)):undefined;setSelectedDef(cell?connection.states.get(cell.stateId)??null:null);};
    connection.addEventListener('status',onStatus);connection.addEventListener('catalog',onCatalog);connection.addEventListener('error',onError);connection.addEventListener('cells',refreshSelection);connection.connect();
    const viewport=new CircuitViewport(viewportRef.current!);view.current=viewport;viewport.onHover=setHover;viewport.onFps=setFps;
    viewport.onPick=(pos,active)=>{
      const {block: name,properties:props}=current.current;const run=callbacks.current.command;
      if(active==='select'){setSelected(pos);viewport.select(pos);const cell=connection.cells.get(posKey(pos));setSelectedDef(cell?connection.states.get(cell.stateId)??null:null);}
      if(active==='place'){const item=connection.catalog.find(c=>c.name===name);const filtered=Object.fromEntries(Object.entries(props).filter(([k,v])=>item?.properties[k]?.includes(v)));run('place',{pos,name,properties:filtered});}
      if(active==='erase')run('remove',{pos});
      if(active==='interact')run('interact',{pos});
      if(active==='probe')run('probe',{pos,name:blockLabel(connection.states.get(connection.cells.get(posKey(pos))?.stateId??0)?.name??'信号')});
    };
    return()=>{viewport.dispose();connection.stop();connection.removeEventListener('status',onStatus);connection.removeEventListener('catalog',onCatalog);connection.removeEventListener('error',onError);connection.removeEventListener('cells',refreshSelection);};
  },[]);
  useEffect(()=>{if(view.current)view.current.tool=tool;},[tool]);
  useEffect(()=>{view.current?.setLayer(layer,cutaway);},[layer,cutaway]);
  useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),6500);return()=>clearTimeout(t);}},[toast]);
  useEffect(()=>{
    const handle=(event:KeyboardEvent)=>{if(event.target instanceof HTMLInputElement||event.target instanceof HTMLSelectElement||event.target instanceof HTMLTextAreaElement)return;
      if(event.code==='Space'){event.preventDefault();command(status.running?'pause':'play');}
      if(event.key==='s'&&!event.metaKey&&!event.ctrlKey)command('step');
      if(event.key==='r'&&!event.metaKey&&!event.ctrlKey)rotate();
      const picked=tools.find(t=>t.key===event.key);if(picked)setTool(picked.id);
      if((event.metaKey||event.ctrlKey)&&event.key==='z'){event.preventDefault();command(event.shiftKey?'redo':'undo');}
      if((event.metaKey||event.ctrlKey)&&event.key==='s'){event.preventDefault();save(false);}
      if((event.metaKey||event.ctrlKey)&&event.key==='c'&&selectedDef){event.preventDefault();setClipboard(selectedDef);notify('已复制器件；选择目标位置后粘贴');}
      if((event.metaKey||event.ctrlKey)&&event.key==='v'&&clipboard){event.preventDefault();setBlock(clipboard.name);setProperties(clipboard.properties);setTool('place');}
      if(event.key==='Delete'||event.key==='Backspace'){if(selected){event.preventDefault();command('remove',{pos:selected});}}
      if(event.key==='Escape'){setTool('select');setSelected(null);view.current?.select(null);setHelp(false);setMenu(false);}
    };window.addEventListener('keydown',handle);return()=>window.removeEventListener('keydown',handle);
  },[status.running,selected,selectedDef,clipboard,properties]);
  const rotate=()=>{const dirs=['north','east','south','west'];setProperties(old=>({...old,facing:dirs[(dirs.indexOf(old.facing??'west')+1)%4]}));};
  const save=async(checkpoint:boolean)=>{const data=await command('save',{checkpoint});if(data){delete data.type;delete data.requestId;delete data.cmd;downloadFile(`${status.name}${checkpoint?'.snapshot': ''}.verimc.json`,JSON.stringify(data,null,2));notify(checkpoint?'运行快照已导出，包含计划事件与内部状态':'电路工程已导出');}};
  const choose=(name:string)=>{setBlock(name);setTool('place');};
  const item=catalog.find(c=>c.name===block);const chosenItem=catalog.find(c=>c.name===selectedDef?.name);
  const filtered=catalog.filter(c=>{const n=shortName(c.name);if(search)return (blockLabel(c.name)+' '+n).toLowerCase().includes(search.toLowerCase());if(category==='常用')return favorites.includes(n);if(category==='器件')return c.device>1;return c.device===1;}).sort((a,b)=>category==='常用'?favorites.indexOf(shortName(a.name))-favorites.indexOf(shortName(b.name)):0);
  return <main className="app">
    <header className="appHeader"><div className="brand"><div className="brandMark"><Cable size={21}/></div><strong>simulator<span> / </span><small>VeriMC</small></strong><span className="alphaBadge">PREVIEW</span></div><div className="projectTitle"><span className="projectDot"/>{status.name}<ChevronDown size={13}/></div><div className="headerRight"><span className="version">JAVA 26.2</span><button className="iconButton" title="使用帮助" onClick={()=>setHelp(true)}><CircleHelp size={17}/></button></div></header>
    <nav className="toolbar"><div className="fileTools"><div className="menuAnchor"><button className="textButton" onClick={()=>setMenu(!menu)}><FolderOpen size={16}/>工程<ChevronDown size={12}/></button>{menu&&<div className="dropdown"><button onClick={()=>{command('new');setMenu(false);setSelected(null);}}>新建空白电路</button><button onClick={()=>{command('demo');setMenu(false);setTimeout(()=>view.current?.fit(),200);}}>打开入门样例</button><button onClick={()=>{command('demo',{kind:'pistons'});setMenu(false);setTimeout(()=>view.current?.fit(),200);}}>打开活塞实验</button><button onClick={()=>{command('demo',{kind:'environment'});setMenu(false);setTimeout(()=>view.current?.fit(),200);}}>打开环境实验</button><button onClick={()=>{command('demo',{kind:'inventory'});setMenu(false);setTimeout(()=>view.current?.fit(),200);}}>打开漏斗实验</button><button onClick={()=>{importRef.current?.click();setMenu(false);}}>导入工程 / 快照…</button><button onClick={()=>{save(false);setMenu(false);}}>导出电路工程</button><button onClick={()=>{save(true);setMenu(false);}}>导出运行快照</button></div>}</div><button title="保存工程 ⌘S" onClick={()=>save(false)}><Save size={16}/></button><i className="divider"/><button title="撤销 ⌘Z" disabled={!status.canUndo} onClick={()=>command('undo')}><Undo2 size={16}/></button><button title="重做 ⇧⌘Z" disabled={!status.canRedo} onClick={()=>command('redo')}><Redo2 size={16}/></button></div>
      <div className="transport"><button className={`runButton ${status.running?'running':''}`} onClick={()=>command(status.running?'pause':'play')} disabled={!connected}>{status.running?<Pause size={15} fill="currentColor"/>:<Play size={15} fill="currentColor"/>}{status.running?'暂停':'运行'}<kbd>Space</kbd></button><button title="前进 1 游戏刻 S" onClick={()=>command('step')}><StepForward size={17}/></button><button title="执行下一个计划事件" onClick={()=>command('stepEvent')}><SkipForward size={17}/></button><button title="恢复本轮运行起点" onClick={()=>command('reset')}><RotateCcw size={16}/></button><i className="divider"/><select aria-label="仿真速度" value={status.speed} onChange={e=>command('speed',{value:Number(e.target.value)})}><option value={20}>1× · 20 gt/s</option><option value={200}>10× · 200 gt/s</option><option value={2000}>100× · 2k gt/s</option><option value={0}>不限速</option></select></div>
      <div className="tickReadout"><span>SIM TIME</span><b>{status.tick.toLocaleString()}</b><span>gt</span></div></nav>
    <div className="workspace">
      <aside className="palette"><div className="panelHeading"><span>器件库</span><span className="muted">{catalog.length}</span></div><label className="search"><Search size={14}/><input placeholder="搜索器件或方块 ID" value={search} onChange={e=>setSearch(e.target.value)}/><kbd>/</kbd></label><div className="tabs">{['常用','器件','结构'].map(c=><button className={category===c?'active':''} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div><div className="paletteList">{filtered.map(c=><button key={c.name} className={`paletteItem ${block===c.name?'selected':''}`} onClick={()=>choose(c.name)} title={c.name}><span className={`blockGlyph ${shortName(c.name).includes('redstone')?'red':''}`}>{blockIcon(c.name)}</span><span>{blockLabel(c.name)}<small>{shortName(c.name)}</small></span>{block===c.name&&<i/>}</button>)}</div><div className="paletteNote"><Cpu size={16}/><span>原生 C++ 仿真<br/><small>器件覆盖持续扩展中</small></span></div></aside>
      <section className="centerWorkspace"><div className="viewportArea"><div className="viewportCanvas" ref={viewportRef}/><div className="viewportTop"><span className="sceneBadge"><span className={status.running?'liveDot':'pausedDot'}/>{status.running?'SIMULATING':'EDIT MODE'}<i/>三维工作台</span><div className="viewButtons"><button title="俯视" onClick={()=>view.current?.top()}><Grid2X2 size={15}/></button><button title="适合画面" onClick={()=>view.current?.fit()}><Maximize size={15}/></button></div></div>
        <div className="toolRail">{tools.map(t=><button key={t.id} className={tool===t.id?'active':''} title={`${t.label} [${t.key}]`} onClick={()=>setTool(t.id)}><t.icon size={18}/><kbd>{t.key}</kbd></button>)}</div>
        <div className="layerControl"><Layers size={15}/><span>编辑层 Y</span><button onClick={()=>setLayer(layer-1)}>−</button><input aria-label="编辑层" type="number" value={layer} onChange={e=>setLayer(Math.max(-64,Math.min(319,Number(e.target.value))))}/><button onClick={()=>setLayer(layer+1)}>+</button><i/><button title="隐藏编辑层以上方块" className={cutaway?'active':''} onClick={()=>setCutaway(!cutaway)}><Eye size={15}/></button></div>
        <div className="viewportBottom"><span>右键拖动旋转 · 中键平移 · 滚轮缩放</span><span className="coord">{hover?`X ${hover[0]}   Y ${hover[1]}   Z ${hover[2]}`:'X —   Y —   Z —'}</span></div>
        {status.pauseReason&&<div className="pauseBanner">{status.pauseReason}</div>}
      </div><Waveform status={status} command={command}/></section>
      <aside className="inspector"><div className="panelHeading"><span>{selectedDef?'器件检查':'放置设置'}</span>{selected&&<button title="取消选择" onClick={()=>{setSelected(null);setSelectedDef(null);view.current?.select(null);}}><X size={14}/></button>}</div>
        <div className="inspectorHero"><div className="largeGlyph">{blockIcon(selectedDef?.name??block)}</div><strong>{blockLabel(selectedDef?.name??block)}</strong><code>{shortName(selectedDef?.name??block)}</code></div>
        {selected&&selectedDef?<><div className="inspectorSection"><label className="miniLabel">坐标</label><div className="positionFields">{selected.map((v,i)=><span key={i}><small>{['X','Y','Z'][i]}</small>{v}</span>)}</div><div className="signalMeter"><span>当前信号</span><strong>{connection.cells.get(posKey(selected))?.value??0}<small>/ 15</small></strong></div><div className="meter"><i style={{width:`${(connection.cells.get(posKey(selected))?.value??0)/15*100}%`}}/></div></div>
          <div className="inspectorSection"><label className="miniLabel">方块状态</label>{Object.entries(selectedDef.properties).map(([key,value])=><label className="propertyRow" key={key}><span>{propertyLabels[key]??key}</span><select value={value} onChange={e=>command('place',{pos:selected,name:selectedDef.name,properties:{...selectedDef.properties,[key]:e.target.value}})}>{(chosenItem?.properties[key]??[value]).map(v=><option key={v} value={v}>{valueLabels[v]??v}</option>)}</select></label>)}</div>
          {chosenItem?.supportLevel==='externalStimulus'&&<p className="subtleText" style={{padding:'0 15px'}}>此器件的环境状态由输入面板或方块属性提供。</p>}
          {(chosenItem?.device===17||chosenItem?.device===16)&&<InventoryControls key={posKey(selected)} pos={selected} hopper={chosenItem?.device===16} command={command}/>}
          <EnvironmentControls key={posKey(selected)+selectedDef.name} pos={selected} block={selectedDef} command={command}/>
          <div className="inspectorSection"><button className="wideButton accentOutline" onClick={()=>command('probe',{pos:selected,name:blockLabel(selectedDef.name)})}><Crosshair size={15}/>添加信号探针</button><button className="wideButton" onClick={()=>command('interact',{pos:selected})}><Hand size={15}/>操作器件</button><button className="wideButton" onClick={()=>{setClipboard(selectedDef);notify('器件已复制，点击粘贴进入放置模式');}}><Copy size={14}/>复制器件</button></div>
        </>:<><div className="inspectorSection"><label className="miniLabel">放置属性</label>{['facing','face','delay','mode','type','half'].filter(k=>item?.properties[k]).map(key=><label key={key} className="propertyRow"><span>{propertyLabels[key]??key}</span><select value={properties[key]??item!.properties[key][0]} onChange={e=>setProperties(old=>({...old,[key]:e.target.value}))}>{item!.properties[key].map(v=><option value={v} key={v}>{valueLabels[v]??v}</option>)}</select></label>)}<button className="wideButton" onClick={rotate}><RotateCw size={15}/>旋转方向<kbd>R</kbd></button><p className="subtleText">中继器、比较器的“朝向”指向输入端。侦测器的朝向指向检测面。</p></div><div className="inspectorSection"><label className="miniLabel">搭建起点</label><button className="wideButton" onClick={()=>{const blocks=[];for(let x=-2;x<=13;x++)for(let z=-2;z<=9;z++)blocks.push({pos:[x,layer-1,z],name:'minecraft:white_concrete'});command('edit',{blocks});}}><Plus size={15}/>铺设 16 × 12 底板</button><p className="subtleText">方块放在当前编辑层。粉线、火把和中继器需要下方支撑。</p>{clipboard&&<button className="wideButton" onClick={()=>{setBlock(clipboard.name);setProperties(clipboard.properties);setTool('place');}}><ClipboardPaste size={15}/>粘贴 {blockLabel(clipboard.name)}</button>}</div></>}
        <div className="inspectorFooter"><span className="miniLabel">运行状态</span><div><span>计划事件</span><code>{status.pending.toLocaleString()}</code></div><div><span>分块存储</span><code>{(status.storageBytes/1048576).toFixed(2)} MB</code></div><div><span>已处理事件</span><code>{status.events.toLocaleString()}</code></div></div>
      </aside>
    </div>
    <footer className="statusBar"><span><i className={connected?'connectionDot':'disconnectedDot'}/>{connected?'本地内核已连接':'正在连接本地内核…'}</span><span>{status.blocks.toLocaleString()} 方块<i/> {fps} FPS<i/> {Math.round(status.measuredTps).toLocaleString()} gt/s</span><span>Java 26.2 · 非实验性红石<i/>工程文件与运行快照</span></footer>
    <input ref={importRef} type="file" accept=".json" hidden onChange={async e=>{const file=e.target.files?.[0];if(file){try{const project=JSON.parse(await file.text());await command('load',{project});setTimeout(()=>view.current?.fit(),200);}catch{notify('工程文件不是有效的 JSON');}}e.target.value='';}}/>
    {toast&&<div className="toast"><span>{toast}</span><button onClick={()=>setToast('')}><X size={15}/></button></div>}
    {help&&<div className="modalBackdrop" onClick={()=>setHelp(false)}><div className="helpModal" onClick={e=>e.stopPropagation()}><button className="modalClose" onClick={()=>setHelp(false)}><X size={18}/></button><span className="eyebrow">YOUR REDSTONE WORKBENCH</span><h1>从一条信号开始。</h1><p>浏览器负责搭建与显示，本地 C++ 内核执行电路。示波器保留游戏刻内的信号变化。</p><div className="helpSteps"><div><b>01</b><strong>搭建电路</strong><p>器件库选择方块，在当前 Y 层左键放置。用右侧按钮快速铺底板，R 调整朝向。</p></div><div><b>02</b><strong>驱动与运行</strong><p>选择操作工具点击拉杆或按钮，Space 运行，S 前进 1 gt。器件编辑会暂停运行。</p></div><div><b>03</b><strong>检查信号</strong><p>探针工具点击方块，下方查看 0–15 信号。探针菜单可设置上升沿或下降沿断点。</p></div></div><p className="subtleText">预览版本只开放已实现的器件。活塞已经开放，容器等器件正在开发，当前不宣称完整兼容。电路文件保存方块设计，运行快照还包含队列和器件内部状态。</p><button className="runButton" onClick={()=>setHelp(false)}>开始搭建<ExternalLink size={14}/></button></div></div>}
  </main>;
}
createRoot(document.getElementById('root')!).render(<App/>);
