grammar verimcGrammar;
// Execution grammar for language 0.1. Keep syntax aligned with verimcGrammar.lark.
sourceFile: BOM? 'language' STRING ';' 'package' qualifiedName ';' importDecl* declaration* EOF;
importDecl: 'import' STRING 'as' IDENT ';';
declaration: constDecl | enumDecl | functionDecl | moduleDecl | cellDecl | buildDecl | testDecl;
name: IDENT | 'reset';
qualifiedName: IDENT ('::' IDENT)*;
valueName: name ('::' IDENT)*;
reference: name referenceSuffix*;
referenceSuffix: '.' name | '[' expr ']' | '[' expr ':' expr ']';
constDecl: 'const' name ':' type '=' expr ';';
enumDecl: 'enum' IDENT '{' IDENT (',' IDENT)+ '}';
functionDecl: 'fn' IDENT '(' functionParams? ')' '->' type '{' letStmt* 'return' expr ';' '}';
functionParams: functionParam (',' functionParam)*;
functionParam: name ':' type;
parameters: '(' (parameter (',' parameter)*)? ')';
parameter: name ':' compileType ('=' expr)?;
compileType: 'nat' | 'integer' | 'bit';
moduleRef: qualifiedName ('(' (namedArg (',' namedArg)*)? ')')?;
namedArg: name '=' expr;
moduleDecl: 'module' IDENT parameters? '{' moduleItem* '}';
moduleItem: portDecl | regDecl | onBlock | generateItem;
generateItem: constDecl | requireStmt | wireDecl | instDecl | unusedStmt | connectStmt | combBlock | generateBlock;
portDecl: ('input' | 'output') name ':' type ';';
wireDecl: 'wire' name ':' type ';';
regDecl: 'reg' name ':' type 'reset' expr ';';
requireStmt: 'require' expr ';';
instDecl: 'inst' name ':' moduleRef ';';
unusedStmt: 'unused' reference ';';
connectStmt: 'connect' reference '=' expr ';';
generateBlock: 'generate' name 'for' name 'in' expr '..' expr '{' generateItem* '}';
combBlock: 'comb' combBody;
combBody: '{' combStmt* '}';
combStmt: assignment | letStmt | combIf | combMatch;
assignment: reference '=' expr ';';
letStmt: 'let' name '=' expr ';';
combIf: 'if' expr combBody ('else' (combBody | combIf))?;
combMatch: 'match' expr '{' combCase+ combDefault? '}';
combCase: 'case' expr combBody;
combDefault: 'default' combBody;
onBlock: 'on' 'rising' '(' reference ')' 'reset' '(' expr ')' seqBody;
seqBody: '{' seqStmt* '}';
seqStmt: nextStmt | letStmt | seqIf | seqMatch;
nextStmt: 'next' name '=' expr ';';
seqIf: 'if' expr seqBody ('else' (seqBody | seqIf))?;
seqMatch: 'match' expr '{' seqCase+ seqDefault? '}';
seqCase: 'case' expr seqBody;
seqDefault: 'default' seqBody;
type: ('bit' | 'level' | 'clock' | 'nat' | 'integer')
    | ('bits' | 'uint' | 'int') '<' sizeExpr '>' | qualifiedName | '[' type ';' sizeExpr ']';
sizeExpr: sizeSum;
sizeSum: sizeProduct (('+' | '-') sizeProduct)*;
sizeProduct: sizeUnary (('*' | '/' | '%') sizeUnary)*;
sizeUnary: ('+' | '-') sizeUnary | sizeAtom;
sizeAtom: INTEGER | qualifiedName '(' (sizeExpr (',' sizeExpr)*)? ')' | valueName | '(' sizeExpr ')';
expr: conditional;
conditional: logicalOr ('?' expr ':' conditional)?;
logicalOr: logicalAnd ('||' logicalAnd)*;
logicalAnd: bitOr ('&&' bitOr)*;
bitOr: bitXor ('|' bitXor)*;
bitXor: bitAnd ('^' bitAnd)*;
bitAnd: equality ('&' equality)*;
equality: relation (('==' | '!=') relation)?;
relation: shift (('<' | '<=' | '>' | '>=') shift)?;
shift: sum (('<<' | '>>') sum)*;
sum: product (('+' | '-') product)*;
product: unary (('*' | '/' | '%') unary)*;
unary: ('!' | '~' | '-' | '+') unary | postfix;
postfix: atom referenceSuffix*;
atom: INTEGER | 'true' | 'false' | call | valueName | '(' expr ')' | arrayExpr;
call: qualifiedName '(' (expr (',' expr)*)? ')';
arrayExpr: '[' expr (',' expr)* ']';
cellDecl: 'cell' IDENT '{' portDecl* 'source' STRING ';' '}';
buildDecl: 'build' IDENT 'for' moduleRef '{' buildItem* '}';
buildItem: 'target' STRING ';' | 'library' STRING ';' | 'bounds' coordinate '..' coordinate ';'
 | 'clock' reference '{' 'period' duration ';' 'high' duration ';' '}'
 | 'input' reference '{' 'setup' duration ';' 'hold' duration ';' '}'
 | 'output' reference '{' 'settle' duration ';' '}'
 | 'port' reference 'at' coordinate 'face' face ('stride' coordinate)? ';'
 | 'map' reference 'using' STRING ';' | 'place' reference 'at' coordinate 'facing' facing ';'
 | 'route' 'auto' ';' | 'objective' ('volume' | 'materials') ';';
coordinate: '(' expr ',' expr ',' expr ')';
duration: sizeExpr ('gt' | 'rt');
face: facing | 'up' | 'down';
facing: 'north' | 'south' | 'west' | 'east';
testDecl: 'test' IDENT 'for' moduleRef 'mode' testMode '{' testBody '}';
testMode: 'logical' | 'physical';
testBody: cycleItem* | watchStmt* atBlock+;
cycleItem: driveStmt | expectStmt | cycleStmt | sampleStmt | watchStmt | letStmt | repeatStmt;
driveStmt: 'drive' reference '=' expr ';';
expectStmt: 'expect' expr ('message' STRING)? ';';
cycleStmt: 'cycle' reference ';';
sampleStmt: 'sample' ';';
watchStmt: 'watch' reference ';';
repeatStmt: 'repeat' sizeExpr '{' cycleItem* '}';
atBlock: 'at' duration '{' (driveStmt | expectStmt)* '}';
BOM: '\uFEFF';
INTEGER: '0x' HEX ('_'? HEX)* | '0b' [01] ('_'? [01])* | [1-9] ('_'? [0-9])* | '0';
fragment HEX: [0-9a-fA-F];
STRING: '"' (~["\\\u0000-\u001F] | '\\' (["\\/bfnrt] | 'u' HEX HEX HEX HEX))* '"';
IDENT: [A-Za-z] [A-Za-z0-9_]*;
WS: [ \t\f\r\n]+ -> skip;
LINE_COMMENT: '//' ~[\r\n]* -> skip;
BLOCK_COMMENT: '/*' .*? '*/' -> skip;
