# Exact generator/runtime pair. Downloads remain in the subproject cache.
set(verimcDependencyCache "${CMAKE_CURRENT_SOURCE_DIR}/.cache" CACHE PATH "VeriMC dependency cache")
function(verimcFetch filename digest)
  set(destination "${verimcDependencyCache}/${filename}")
  if(EXISTS "${destination}")
    file(SHA256 "${destination}" actual)
    if(NOT actual STREQUAL digest)
      message(FATAL_ERROR "Checksum mismatch: ${destination}")
    endif()
  else()
    file(DOWNLOAD "https://www.antlr.org/download/${filename}" "${destination}"
      EXPECTED_HASH "SHA256=${digest}" TLS_VERIFY ON STATUS downloadStatus)
    list(GET downloadStatus 0 downloadCode)
    if(NOT downloadCode EQUAL 0)
      file(REMOVE "${destination}")
      message(FATAL_ERROR "ANTLR download failed: ${downloadStatus}")
    endif()
  endif()
endfunction()
file(MAKE_DIRECTORY "${verimcDependencyCache}")
verimcFetch(antlr-4.13.2-complete.jar eae2dfa119a64327444672aff63e9ec35a20180dc5b8090b7a6ab85125df4d76)
verimcFetch(antlr4-cpp-runtime-4.13.2-source.zip 0ed13668906e86dbc0dcddf30fdee68c10203dea4e83852b4edb810821bee3c4)
# Extract from the verified archive into this build, not a mutable system installation.
set(verimcAntlrSource "${CMAKE_CURRENT_BINARY_DIR}/antlrRuntime")
if(NOT EXISTS "${verimcAntlrSource}/VERSION")
  file(ARCHIVE_EXTRACT INPUT "${verimcDependencyCache}/antlr4-cpp-runtime-4.13.2-source.zip" DESTINATION "${verimcAntlrSource}")
endif()
set(ANTLR_BUILD_CPP_TESTS OFF CACHE BOOL "" FORCE)
set(ANTLR_BUILD_SHARED OFF CACHE BOOL "" FORCE)
set(ANTLR_BUILD_STATIC ON CACHE BOOL "" FORCE)
set(WITH_DEMO OFF CACHE BOOL "" FORCE)
add_subdirectory("${verimcAntlrSource}" "${CMAKE_CURRENT_BINARY_DIR}/antlrBuild" EXCLUDE_FROM_ALL)
set(verimcGeneratedDir "${CMAKE_CURRENT_BINARY_DIR}/generated")
set(verimcGeneratedSources "${verimcGeneratedDir}/verimcGrammarLexer.cpp" "${verimcGeneratedDir}/verimcGrammarParser.cpp")
add_custom_command(OUTPUT ${verimcGeneratedSources} "${verimcGeneratedDir}/verimcGrammarLexer.h" "${verimcGeneratedDir}/verimcGrammarParser.h"
  COMMAND ${CMAKE_COMMAND} -E make_directory "${verimcGeneratedDir}"
  COMMAND ${Java_JAVA_EXECUTABLE} -jar "${verimcDependencyCache}/antlr-4.13.2-complete.jar" -Dlanguage=Cpp -no-listener -no-visitor -Xexact-output-dir -o "${verimcGeneratedDir}" "${CMAKE_CURRENT_SOURCE_DIR}/grammar/verimcGrammar.g4"
  DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/grammar/verimcGrammar.g4" "${verimcDependencyCache}/antlr-4.13.2-complete.jar" VERBATIM)
add_library(verimcParser STATIC ${verimcGeneratedSources})
target_include_directories(verimcParser SYSTEM PUBLIC "${verimcGeneratedDir}")
target_link_libraries(verimcParser PUBLIC antlr4_static)
